/**
 * Hire-talent mega menus — professionals to hire (not job titles).
 * Layout mirrors Find Work columns; links go to /hire/* landings (see mega-menu-landing-paths).
 */

import type {
  FreelanceJobsMegaMenuKey,
  FreelanceJobsMegaMenuColumns,
} from './freelance-jobs.mega-menu'
import { hireMegaMenuHrefFromFilters } from './mega-menu-landing-paths'

const BF = hireMegaMenuHrefFromFilters

const H = (slug: string): string => `/hire/${slug}`

export const HIRE_TALENT_MEGA_MENU: Record<FreelanceJobsMegaMenuKey, FreelanceJobsMegaMenuColumns> = {
  dev: [
    [
      {
        heading: 'Data Science & Analytics',
        links: [
          { label: 'Data Analysts', href: BF('data-science', 'analyst') },
          { label: 'Data Scientists', href: H('machine-learning-engineers') },
          { label: 'Microsoft Power BI Specialists', href: BF('data-science', 'power bi') },
          { label: 'Data Engineers', href: BF('data-science', 'engineer') },
          { label: 'Tableau Developers', href: BF('data-science', 'tableau') },
          { label: 'Data Visualization Consultants', href: BF('data-science', 'visualization') },
          { label: 'R Developers & Programmers', href: BF('data-science', 'r') },
          { label: 'Machine Learning Engineers', href: H('machine-learning-engineers') },
        ],
      },
      {
        heading: 'E-commerce Development',
        links: [
          { label: 'Shopify Developers', href: BF('web-development', 'shopify') },
          { label: 'E-commerce Developers', href: BF('web-development', 'ecommerce') },
          { label: 'Squarespace Developers', href: BF('web-development', 'squarespace') },
          { label: 'WooCommerce Developers', href: H('wordpress-developers') },
          { label: 'Magento Developers', href: BF('web-development', 'magento') },
        ],
      },
      {
        heading: 'Emerging Tech',
        links: [
          { label: 'Generative AI Specialists', href: H('machine-learning-engineers') },
          { label: 'Prompt Engineers', href: BF('data-science', 'prompt engineering') },
          { label: 'AI Content Creators', href: H('content-writers') },
          { label: 'ChatGPT Specialists', href: H('chatbot-developers') },
          { label: 'GPT-3 Specialists', href: H('machine-learning-engineers') },
          { label: 'Midjourney Artists', href: H('graphic-designers') },
          { label: 'AI Chatbot Specialists', href: H('chatbot-developers') },
          { label: 'Computer Vision Engineers', href: H('computer-vision-engineers') },
          { label: 'Google BERT Specialists', href: BF('data-science', 'bert') },
        ],
      },
    ],
    [
      {
        heading: 'Game Development',
        links: [
          { label: 'Game Developers', href: BF('game-development') },
          { label: 'Unity Developers', href: BF('game-development', 'unity') },
          { label: 'Unreal Engine Developers', href: BF('game-development', 'unreal') },
          { label: 'Game Designers', href: BF('game-development', 'designer') },
          { label: 'Virtual Reality Developers', href: BF('game-development', 'vr') },
          { label: 'Augmented Reality Developers', href: BF('game-development', 'ar') },
        ],
      },
      {
        heading: 'IT & Networking',
        links: [
          { label: 'Database Administrators', href: BF('web-development', 'database administrator') },
          { label: 'Technical Support Specialists', href: BF('marketing', 'technical support') },
          { label: 'Penetration Testers', href: H('ethical-hackers') },
          { label: 'Information Security Analysts', href: H('ethical-hackers') },
          { label: 'Network Engineers', href: BF('web-development', 'network') },
          { label: 'AWS Developers', href: BF('web-development', 'aws') },
          { label: 'Cloud Computing Specialists', href: BF('web-development', 'cloud') },
          { label: 'System Administrators', href: BF('web-development', 'system administrator') },
        ],
      },
      {
        heading: 'Mobile App Development',
        links: [
          { label: 'Mobile App Developers', href: H('mobile-app-developers') },
          { label: 'Flutter Developers', href: BF('mobile-apps', 'flutter') },
          { label: 'Android Developers', href: BF('mobile-apps', 'android') },
          { label: 'Android App Developers', href: BF('mobile-apps', 'android app') },
          { label: 'iOS Developers', href: BF('mobile-apps', 'ios') },
          { label: 'API Developers', href: BF('web-development', 'api') },
        ],
      },
    ],
    [
      {
        heading: 'Development',
        links: [
          { label: 'Microsoft Access Developers', href: BF('web-development', 'microsoft access') },
          { label: 'Git Developers', href: BF('web-development', 'git') },
          { label: 'SQL Developers', href: BF('web-development', 'sql') },
          { label: 'Full Stack Developers', href: H('web-developers') },
          { label: 'Software Developers', href: H('software-developers') },
          { label: 'React.js Developers', href: BF('web-development', 'react') },
          { label: 'Python Developers', href: H('python-developers') },
          { label: 'Java Developers', href: BF('web-development', 'java') },
          { label: 'DevOps Engineers', href: BF('web-development', 'devops') },
          { label: 'React Native Developers', href: BF('mobile-apps', 'react native') },
          { label: 'Django Developers', href: BF('web-development', 'django') },
          { label: 'Node.js Developers & Programmers', href: BF('web-development', 'node') },
          { label: '.NET Developers', href: BF('web-development', 'dotnet') },
          { label: 'Golang Developers', href: BF('web-development', 'golang') },
          { label: 'C# Developers & Programmers', href: BF('web-development', 'c#') },
          { label: 'Vue.js Developers', href: BF('web-development', 'vue') },
          { label: 'Angular Developers', href: BF('web-development', 'angular') },
        ],
      },
    ],
    [
      {
        heading: 'Web Development & Design',
        links: [
          { label: 'Web Designers', href: H('web-designers') },
          { label: 'Figma Designers', href: H('graphic-designers') },
          { label: 'Webflow Developers', href: BF('web-development', 'webflow') },
          { label: 'UI Designers', href: H('ux-designers') },
          { label: 'Laravel Developers', href: BF('web-development', 'laravel') },
          { label: 'Wix Developers', href: BF('web-development', 'wix') },
          { label: 'Next.js Developers', href: BF('web-development', 'next.js') },
          { label: 'Web Developers', href: H('web-developers') },
          { label: 'WordPress Developers', href: H('wordpress-developers') },
          { label: 'UX Designers', href: H('ux-designers') },
          { label: 'Front-End Developers', href: BF('web-development', 'frontend') },
          { label: 'PHP Developers', href: BF('web-development', 'php') },
          { label: 'Back-End Developers', href: BF('web-development', 'backend') },
          { label: 'E-Commerce Experts', href: BF('web-development', 'ecommerce') },
          { label: 'CSS Developers', href: BF('web-development', 'css') },
          { label: 'Ruby on Rails Developers', href: BF('web-development', 'ruby on rails') },
          { label: 'C++ Programmers & Developers', href: BF('web-development', 'c++') },
          { label: 'JavaScript Developers', href: BF('web-development', 'javascript') },
        ],
      },
      {
        heading: 'Other',
        links: [
          { label: 'Salesforce Experts', href: BF('web-development', 'salesforce') },
          { label: 'Product Managers', href: BF('marketing', 'product manager') },
          { label: 'QA Engineers', href: BF('web-development', 'qa') },
          { label: 'Certified Ethical Hackers', href: H('ethical-hackers') },
          { label: 'Automation Engineers', href: H('automation-engineers') },
          { label: 'Blockchain Developers', href: BF('web-development', 'blockchain') },
          { label: 'AI Engineers', href: H('machine-learning-engineers') },
          { label: 'Excel Developers', href: BF('web-development', 'excel') },
        ],
      },
    ],
  ],

  ai: [
    [
      {
        heading: 'AI Writing',
        links: [
          { label: 'AI Writers', href: H('content-writers') },
          { label: 'AI Content Creators', href: H('copywriters') },
          { label: 'AI Content Editors', href: BF('data-science', 'ai content editing') },
        ],
      },
      {
        heading: 'AI Art',
        links: [
          { label: 'AI Artists', href: BF('design', 'ai art') },
          { label: 'Midjourney AI Artists', href: H('graphic-designers') },
          { label: 'StableDiffusion Artists', href: BF('design', 'stable diffusion') },
        ],
      },
    ],
    [
      {
        heading: 'AI Development',
        links: [
          { label: 'AI Developers', href: H('chatbot-developers') },
          { label: 'Prompt Engineering Specialists', href: BF('data-science', 'prompt engineering') },
          { label: 'AI Engineers', href: H('machine-learning-engineers') },
          { label: 'Generative AI Experts', href: H('machine-learning-engineers') },
          { label: 'AI Chatbot Specialists', href: H('chatbot-developers') },
          { label: 'Machine Learning Engineers', href: H('machine-learning-engineers') },
          { label: 'Azure OpenAI Specialists', href: BF('data-science', 'azure openai') },
          { label: 'AI Text-to-Image Specialists', href: BF('data-science', 'text to image') },
          { label: 'AI Text-to-Speech Specialists', href: BF('data-science', 'text to speech') },
          { label: 'OpenAI Codex Specialists', href: H('chatbot-developers') },
          { label: 'Natural Language Processing', href: BF('data-science', 'natural language processing') },
          { label: 'Autoencoder Specialists', href: BF('data-science', 'autoencoder') },
          { label: 'Variational Autoencoder Specialists', href: BF('data-science', 'variational autoencoder') },
          { label: 'Computer Vision Engineers', href: H('computer-vision-engineers') },
          { label: 'Automation Engineers', href: H('automation-engineers') },
        ],
      },
    ],
    [
      {
        heading: 'AI & Data Services',
        links: [
          { label: 'Data Scientists', href: H('machine-learning-engineers') },
          { label: 'Data Annotators', href: BF('data-science', 'annotation') },
        ],
      },
    ],
    [
      {
        heading: 'Other',
        links: [
          { label: 'ChatGPT Specialists', href: H('chatbot-developers') },
          { label: 'AI Consultants', href: BF('data-science', 'ai consulting') },
          { label: 'Google BERT Specialists', href: BF('data-science', 'bert') },
          { label: 'GPT-4 Specialists', href: H('machine-learning-engineers') },
          { label: 'AI Researchers', href: BF('data-science', 'ai research') },
          { label: 'Generative Adversarial Network Specialists', href: BF('data-science', 'generative adversarial network') },
          { label: 'Gradio Specialists', href: BF('data-science', 'gradio') },
          { label: 'Hugging Face Specialists', href: BF('data-science', 'hugging') },
          { label: 'Replit Specialists', href: BF('web-development', 'replit') },
          { label: 'Streamlit Specialists', href: BF('data-science', 'streamlit') },
          { label: 'BLOOM Specialists', href: BF('data-science', 'bloom') },
          { label: 'GPT Neo Specialists', href: BF('data-science', 'gpt neo') },
          { label: 'GPT-J Specialists', href: BF('data-science', 'gpt-j') },
          { label: 'Deep Learning Engineers', href: BF('data-science', 'deep learning') },
          { label: 'TensorFlow Specialists', href: BF('data-science', 'tensorflow') },
        ],
      },
    ],
  ],

  design: [
    [
      {
        heading: 'Animation',
        links: [
          { label: 'Animators', href: H('animators') },
          { label: 'Motion Graphics Designers', href: H('video-editors') },
          { label: 'Blender3D Specialists', href: BF('video', 'blender') },
          { label: '3D Animators', href: BF('video', '3d animation') },
          { label: '2D Animators', href: BF('video', '2d animation') },
          { label: 'Video Animation Professionals', href: H('video-editors') },
          { label: 'Anime Artists', href: BF('design', 'anime') },
          { label: 'Visual Effects Artists', href: BF('video', 'vfx') },
          { label: 'Adobe After Effects Specialists', href: BF('design', 'after effects') },
        ],
      },
      {
        heading: 'Audio production',
        links: [
          { label: 'Audiobook Narrators', href: H('voice-actors') },
          { label: 'Audio Engineers', href: H('audio-editors') },
          { label: 'Audio Editors', href: H('audio-editors') },
          { label: 'Music Composers', href: H('music-producers') },
          { label: 'Sound Engineers', href: BF('video', 'sound engineer') },
          { label: 'Music Producers', href: H('music-producers') },
          { label: 'Music Video Professionals', href: H('video-editors') },
        ],
      },
    ],
    [
      {
        heading: 'Fashion design',
        links: [
          { label: 'Fashion Designers', href: BF('design', 'fashion') },
          { label: 'Sewing Professionals', href: BF('design', 'sewing') },
          { label: 'Jewelry Designers', href: BF('design', 'jewelry') },
          { label: 'Fashion Illustrators', href: H('illustrators') },
          { label: 'Fashion Models', href: BF('design', 'fashion model') },
        ],
      },
      {
        heading: 'Graphic design',
        links: [
          { label: 'Graphic Designers', href: H('graphic-designers') },
          { label: 'Logo Designers', href: H('logo-designers') },
          { label: 'Canva Designers', href: H('graphic-designers') },
          { label: '3D modelers', href: BF('design', '3d model') },
          { label: 'T-Shirt Designers', href: BF('design', 't-shirt') },
          { label: '3D Designers', href: BF('design', '3d designer') },
          { label: 'Presentation Designers', href: BF('design', 'presentation') },
          { label: 'Book Cover Designers', href: BF('design', 'book cover') },
          { label: 'Brand Consulting Specialists', href: BF('design', 'brand consulting') },
          { label: 'Packaging Designers', href: BF('design', 'packaging') },
          { label: '2D Game Art Professionals', href: BF('game-development', '2d art') },
          { label: 'Game Designers', href: BF('game-development', 'designer') },
          { label: 'Poster Designers', href: BF('design', 'poster') },
          { label: 'Business Card Designers', href: BF('design', 'business card') },
          { label: 'Social Media Designers', href: H('social-media-managers') },
          { label: 'Banner Designers', href: BF('design', 'banner') },
          { label: 'Flyer Designers', href: BF('design', 'flyer') },
          { label: 'Adobe InDesign Experts', href: BF('design', 'indesign') },
        ],
      },
    ],
    [
      {
        heading: 'Illustration',
        links: [
          { label: 'Adobe Illustrator Experts', href: H('illustrators') },
          { label: 'Illustrators', href: H('illustrators') },
          { label: 'Product Designers', href: H('ux-designers') },
          { label: "Children's Book Illustrators", href: BF('design', 'children book') },
          { label: 'Drawer', href: BF('design', 'drawing') },
          { label: 'Character Designers', href: BF('design', 'character') },
          { label: 'Infographic Designers', href: BF('design', 'infographic') },
        ],
      },
      {
        heading: 'Interior design',
        links: [
          { label: 'Architects', href: BF('web-development', 'architecture') },
          { label: 'Interior Designers', href: BF('design', 'interior') },
          { label: 'Landscape Designers', href: BF('design', 'landscape') },
          { label: 'Floor Plan Designers', href: BF('design', 'floor plan') },
          { label: 'Furniture Design Professionals', href: BF('design', 'furniture') },
        ],
      },
      {
        heading: 'Video production',
        links: [
          { label: 'Video Editors', href: H('video-editors') },
          { label: 'Videographers', href: BF('video', 'videographer') },
          { label: 'Video Producers', href: BF('video', 'video production') },
          { label: 'Film Directors', href: BF('video', 'film director') },
          { label: 'Actors', href: BF('video', 'actor') },
        ],
      },
    ],
    [
      {
        heading: 'Other',
        links: [
          { label: 'Voice Talent', href: H('voice-actors') },
          { label: 'Photo Editors', href: BF('design', 'photo editing') },
          { label: 'Adobe Photoshop Experts', href: BF('design', 'photoshop') },
          { label: 'Photographers', href: BF('design', 'photographer') },
          { label: 'Voice Actors', href: H('voice-actors') },
          { label: 'Photo Retouchers', href: BF('design', 'retouch') },
          { label: 'Product Photographers', href: BF('design', 'product photo') },
          { label: 'Creative Directors', href: BF('design', 'creative director') },
          { label: 'Manga Artists', href: BF('design', 'manga') },
          { label: 'Digital Artists', href: BF('design', 'digital art') },
          { label: 'Comic Artists', href: BF('design', 'comic') },
          { label: 'Cartoonists', href: BF('design', 'cartoon') },
          { label: 'Instructional Designers', href: BF('design', 'instructional') },
        ],
      },
    ],
  ],

  marketing: [
    [
      {
        heading: 'Analytics',
        links: [
          { label: 'Data Analysts', href: BF('data-science', 'analyst') },
          { label: 'Google Analytics Experts', href: BF('marketing', 'google analytics') },
          { label: 'Marketing Strategists', href: BF('marketing', 'strategy') },
          { label: 'Google Tag Manager Specialists', href: BF('marketing', 'google tag manager') },
          { label: 'Customer Insights Analysts', href: BF('marketing', 'customer insights') },
          { label: 'Marketing Researchers', href: BF('marketing', 'research') },
          { label: 'Marketing Automation Experts', href: BF('marketing', 'marketing automation') },
          { label: 'Web Analysts', href: BF('marketing', 'web analyst') },
        ],
      },
      {
        heading: 'Email marketing',
        links: [
          { label: 'SendGrid Specialists', href: BF('marketing', 'sendgrid') },
          { label: 'Klaviyo Experts', href: BF('marketing', 'klaviyo') },
          { label: 'Email Marketers', href: H('email-marketers') },
          { label: 'Mailchimp Specialists', href: BF('marketing', 'mailchimp') },
        ],
      },
      {
        heading: 'Branding',
        links: [
          { label: 'Brand Consulting Specialists', href: BF('marketing', 'brand consulting') },
          { label: 'Branding Professionals', href: BF('design', 'branding') },
          { label: 'Brand Identity Designers', href: BF('design', 'brand identity') },
          { label: 'Brand Managers', href: BF('marketing', 'brand manager') },
          { label: 'Go-to-Market Strategists', href: BF('marketing', 'gtm') },
          { label: 'Brand Marketers', href: BF('marketing', 'brand marketing') },
          { label: 'Corporate Brand Identity Specialists', href: BF('design', 'corporate brand') },
        ],
      },
    ],
    [
      {
        heading: 'Content marketing',
        links: [
          { label: 'Content Writers', href: H('content-writers') },
          { label: 'Blog Writers', href: BF('writing', 'blog') },
          { label: 'Content Marketers', href: H('digital-marketers') },
          { label: 'Content Creators', href: BF('marketing', 'content creator') },
          { label: 'Content Strategists', href: BF('marketing', 'content strategist') },
          { label: 'Website Content Managers', href: BF('marketing', 'website content') },
        ],
      },
      {
        heading: 'Digital marketing',
        links: [
          { label: 'Digital Marketers', href: H('digital-marketers') },
          { label: 'Lead Generation Experts', href: H('lead-generation-specialists') },
          { label: 'HubSpot Experts', href: BF('marketing', 'hubspot') },
          { label: 'Digital Strategists', href: BF('marketing', 'digital strategist') },
          { label: 'Growth Marketers', href: BF('marketing', 'growth') },
          { label: 'Inbound Marketers', href: BF('marketing', 'inbound') },
          { label: 'Integrated Marketers', href: BF('marketing', 'integrated') },
          { label: 'Omnichannel Marketers', href: BF('marketing', 'omnichannel') },
          { label: 'Digital Media Specialists', href: BF('marketing', 'digital media') },
          { label: 'E-commerce Consultants', href: BF('marketing', 'ecommerce consultant') },
          { label: 'Media Planners', href: BF('marketing', 'media planner') },
          { label: 'Affiliate Marketers', href: BF('marketing', 'affiliate') },
          { label: 'Conversion Rate Optimizers', href: BF('marketing', 'cro') },
          { label: 'Mobile Marketers', href: BF('marketing', 'mobile marketing') },
          { label: 'Social Video Marketers', href: BF('marketing', 'social video') },
          { label: 'Marketing Consultants', href: BF('marketing', 'consultant') },
          { label: 'Marketing Managers', href: BF('marketing', 'marketing manager') },
          { label: 'Online Community Managers', href: BF('marketing', 'community manager') },
        ],
      },
    ],
    [
      {
        heading: 'SEO/SEM',
        links: [
          { label: 'SEO Experts', href: H('seo-experts') },
          { label: 'Amazon PPC Experts', href: BF('marketing', 'amazon ppc') },
          { label: 'PPC Consultants', href: BF('marketing', 'ppc') },
          { label: 'SEO Keyword Researchers', href: BF('marketing', 'keyword research') },
          { label: 'On-Page SEO Experts', href: BF('marketing', 'on-page seo') },
          { label: 'Campaign Managers', href: BF('marketing', 'campaign manager') },
          { label: 'Link Builders', href: BF('marketing', 'link building') },
          { label: 'Google Ads Experts', href: H('google-ads-experts') },
          { label: 'PPC Advertising Specialists', href: BF('marketing', 'ppc advertising') },
        ],
      },
      {
        heading: 'Social media',
        links: [
          { label: 'Social Media Managers', href: H('social-media-managers') },
          { label: 'Facebook Ads Specialists', href: BF('marketing', 'facebook advertising') },
          { label: 'Instagram Marketers', href: BF('marketing', 'instagram') },
          { label: 'Social Media Consultants', href: BF('marketing', 'social media consultant') },
          { label: 'LinkedIn Campaign Managers', href: BF('marketing', 'linkedin campaign') },
          { label: 'Snapchat Marketers', href: BF('marketing', 'snapchat') },
          { label: 'Social Media Marketers', href: H('social-media-managers') },
          { label: 'YouTube Marketers', href: BF('marketing', 'youtube') },
          { label: 'Influencer Marketers', href: BF('marketing', 'influencer') },
          { label: 'LinkedIn Specialists', href: BF('marketing', 'linkedin') },
          { label: 'Facebook Marketers', href: BF('marketing', 'facebook marketing') },
          { label: 'Facebook Professionals', href: BF('marketing', 'facebook') },
          { label: 'Pinterest Marketers', href: BF('marketing', 'pinterest') },
          { label: 'Twitter Marketers', href: BF('marketing', 'twitter') },
        ],
      },
    ],
    [
      {
        heading: 'Other',
        links: [
          { label: 'Sales Representatives', href: BF('marketing', 'sales representative') },
          { label: 'Cold Callers', href: H('cold-callers') },
          { label: 'Marketers', href: H('digital-marketers') },
          { label: 'Amazon FBA Assistants', href: BF('writing', 'amazon fba') },
          { label: 'Dropshippers', href: BF('marketing', 'dropship') },
          { label: 'Product Marketers', href: BF('marketing', 'product marketer') },
          { label: 'B2B Marketers', href: BF('marketing', 'b2b') },
          { label: 'Competitive Analysts', href: BF('marketing', 'competitive') },
          { label: 'Direct Marketers', href: BF('marketing', 'direct marketing') },
          { label: 'Salesforce Marketing Cloud Specialists', href: BF('marketing', 'salesforce marketing cloud') },
          { label: 'Fractional CMOs', href: BF('marketing', 'fractional cmo') },
          { label: 'Customer Acquisition Strategists', href: BF('marketing', 'customer acquisition') },
          { label: 'PowerPoint Experts', href: BF('design', 'powerpoint') },
          { label: 'Public Relations Specialists', href: BF('marketing', 'pr') },
          { label: 'Media Buyers', href: BF('marketing', 'media buyer') },
          { label: 'Tagline Professionals', href: BF('marketing', 'tagline') },
          { label: 'Telemarketers', href: BF('marketing', 'telemarketing') },
          { label: 'Business Coaches', href: BF('marketing', 'business coach') },
          { label: 'Growth Hackers', href: BF('marketing', 'growth hacker') },
          { label: 'Sales Managers', href: BF('marketing', 'sales manager') },
          { label: 'Sales Copywriters', href: H('copywriters') },
          { label: 'Crowdfunding Specialists', href: BF('marketing', 'crowdfunding') },
        ],
      },
    ],
  ],

  admin: [
    [
      {
        heading: 'Customer service',
        links: [
          { label: 'Social Media Managers', href: H('social-media-managers') },
          { label: 'Phone Support Agents', href: BF('writing', 'phone support') },
          { label: 'Customer Success Managers', href: BF('marketing', 'customer success') },
          { label: 'Customer Service Representatives', href: BF('writing', 'customer service') },
          { label: 'Project Managers', href: BF('marketing', 'project manager') },
          { label: 'Salesforce Experts', href: BF('web-development', 'salesforce') },
          { label: 'Account Managers', href: BF('marketing', 'account manager') },
          { label: 'Customer Support Representatives', href: BF('writing', 'customer support') },
          { label: 'Zendesk Specialists', href: BF('writing', 'zendesk') },
          { label: 'Zoom Video Conferencing Specialists', href: BF('writing', 'zoom') },
          { label: 'Chat Support Specialists', href: BF('marketing', 'social') },
          { label: 'Mailchimp Specialists', href: BF('marketing', 'mailchimp') },
          { label: 'Email Handlers', href: BF('writing', 'email handling') },
        ],
      },
    ],
    [
      {
        heading: 'Data entry',
        links: [
          { label: 'Data Entry Specialists', href: BF('writing', 'data entry') },
          { label: 'Data Annotators', href: BF('data-science', 'annotation') },
          { label: 'Data Analysts', href: BF('data-science', 'analyst') },
          { label: 'Typists', href: BF('writing', 'typing') },
          { label: 'Zoho CRM Specialists', href: BF('writing', 'zoho') },
          { label: 'Auditors', href: BF('finance', 'audit') },
          { label: 'Document Conversion Specialists', href: BF('writing', 'document conversion') },
          { label: 'Data Miners', href: BF('writing', 'data mining') },
          { label: 'Data Collection Specialists', href: BF('writing', 'data collection') },
          { label: 'Excel Experts', href: BF('writing', 'excel') },
          { label: 'Spreadsheets Specialists', href: BF('writing', 'spreadsheet') },
          { label: 'Google Sheets Experts', href: BF('writing', 'google sheets') },
          { label: 'Data Visualization Consultants', href: BF('data-science', 'visualization') },
          { label: 'Data Scrapers', href: BF('web-development', 'web scraping') },
          { label: 'PDF Converters', href: BF('writing', 'pdf conversion') },
          { label: 'Adobe PDF Experts', href: BF('writing', 'adobe pdf') },
        ],
      },
    ],
    [
      {
        heading: 'Personal / Virtual assistance',
        links: [
          { label: 'Virtual Assistants', href: H('virtual-assistants') },
          { label: 'Personal Assistants', href: H('personal-assistants') },
          { label: 'Real Estate Virtual Assistants', href: BF('writing', 'real estate va') },
          { label: 'Amazon Virtual Assistants', href: BF('writing', 'amazon va') },
          { label: 'Cold Callers', href: H('cold-callers') },
          { label: 'Administrative Assistants', href: BF('writing', 'administrative') },
          { label: 'Appointment Setters', href: BF('writing', 'appointment setter') },
          { label: 'Recruiters & Recruitment Consultants', href: BF('marketing', 'recruiter') },
          { label: 'Executive Assistants', href: H('personal-assistants') },
          { label: 'Call Center Agents', href: BF('writing', 'call center') },
          { label: 'Research Specialists', href: BF('writing', 'research') },
          { label: 'Microsoft Office Specialists', href: BF('writing', 'microsoft office') },
          { label: 'Product Upload Professionals', href: BF('writing', 'product upload') },
          { label: 'Transcriptionists', href: BF('writing', 'transcription') },
          { label: 'Stenographers', href: BF('writing', 'stenographer') },
          { label: 'Medical Transcriptionists', href: BF('writing', 'medical transcription') },
          { label: 'Closed Captions Specialists', href: BF('video', 'closed captions') },
          { label: 'Microsoft Word Experts', href: BF('writing', 'microsoft word') },
        ],
      },
    ],
    [
      {
        heading: 'Web research & posting',
        links: [
          { label: 'Web Scrapers', href: BF('web-development', 'web scraping') },
          { label: 'Etsy Administration Specialists', href: BF('writing', 'etsy') },
          { label: 'Amazon Listing Optimization Experts', href: BF('writing', 'amazon listing') },
          { label: 'Internet Researchers', href: BF('writing', 'internet research') },
          { label: 'Web Researchers', href: BF('writing', 'web research') },
          { label: 'eBay Listing writers', href: BF('writing', 'ebay listing') },
          { label: 'eBay Marketers', href: BF('writing', 'ebay marketer') },
          { label: 'Fact Checkers', href: BF('writing', 'fact check') },
        ],
      },
    ],
    [
      {
        heading: 'Trust & safety',
        links: [
          { label: 'Content Moderators', href: H('content-moderators') },
          { label: 'Community Managers', href: BF('marketing', 'community') },
        ],
      },
      {
        heading: 'Other',
        links: [
          { label: 'Bookkeepers', href: BF('finance', 'bookkeep') },
          { label: 'Presentation designers', href: BF('design', 'presentation') },
          { label: 'Google Slides Specialists', href: BF('writing', 'google slides') },
          { label: 'PowerPoint Experts', href: BF('design', 'powerpoint') },
          { label: 'Medical Coders & Billers', href: BF('writing', 'medical billing') },
          { label: 'Paralegals', href: BF('writing', 'paralegal') },
          { label: 'Legal writers', href: BF('writing', 'legal writer') },
          { label: 'Event Planners', href: BF('marketing', 'event planning') },
          { label: 'Travel Planners', href: BF('writing', 'travel planning') },
          { label: 'Event Managers', href: BF('marketing', 'event manager') },
          { label: 'Legal Researchers', href: BF('writing', 'legal research') },
          { label: 'Legal Assistants', href: BF('writing', 'legal assistant') },
        ],
      },
    ],
  ],

  more: [
    [
      {
        heading: '',
        links: [
          { label: 'Writing & Translation', href: H('content-writers') },
          { label: 'Finance & Accounting', href: H('finance-professionals') },
          { label: 'Engineering & Architecture', href: H('software-developers') },
          { label: 'Legal', href: H('legal-professionals') },
          { label: 'HR & Training', href: H('hr-specialists') },
        ],
      },
    ],
    [
      {
        heading: 'Academic Writing',
        links: [
          { label: 'Essay Writers', href: BF('writing', 'essay') },
          { label: 'Academic Writing Specialists', href: BF('writing', 'academic') },
          { label: 'Instructional designers', href: BF('design', 'instructional') },
          { label: 'Course Professionals', href: BF('writing', 'course') },
          { label: 'Curriculum developers', href: BF('writing', 'curriculum') },
        ],
      },
      {
        heading: 'Content Writing',
        links: [
          { label: 'Biography Writers', href: BF('writing', 'biography') },
          { label: 'Ghost Writers', href: H('ghostwriters') },
          { label: 'Book Reviewers', href: BF('writing', 'book review') },
          { label: 'Resume Writers', href: BF('writing', 'resume') },
          { label: 'Job Description Writers', href: BF('writing', 'job description') },
          { label: 'Cover Letter Writers', href: BF('writing', 'cover letter') },
          { label: 'Writers', href: H('content-writers') },
          { label: 'Business Plan Writers', href: BF('writing', 'business plan') },
          { label: 'Market Research Analysts', href: BF('marketing', 'research') },
          { label: 'Medical Writers', href: BF('writing', 'medical') },
          { label: 'Legal Writers', href: BF('writing', 'legal writer') },
          { label: 'Researchers', href: BF('writing', 'research') },
          { label: 'Research Specialists', href: BF('writing', 'research specialist') },
          { label: 'Fashion Writers', href: BF('writing', 'fashion') },
          { label: 'Letter Writers', href: BF('writing', 'letter') },
        ],
      },
    ],
    [
      {
        heading: 'Creative Writing',
        links: [
          { label: 'Book Writers', href: H('ghostwriters') },
          { label: 'Fiction Writers', href: BF('writing', 'fiction') },
          { label: 'Short Story Writers', href: BF('writing', 'short story') },
          { label: 'Kindle Direct Publishing Professionals', href: BF('writing', 'kindle') },
          { label: 'Creative Writers', href: BF('writing', 'creative') },
          { label: 'Comedy Writers', href: BF('writing', 'comedy') },
          { label: 'Screenwriters', href: BF('writing', 'screenplay') },
          { label: 'Podcasting Producers', href: BF('video', 'podcast') },
          { label: 'Scriptwriting Professionals', href: BF('writing', 'script') },
          { label: 'Speech Writers', href: BF('writing', 'speech') },
          { label: 'Storyboard Artists', href: BF('design', 'storyboard') },
        ],
      },
      {
        heading: 'Editing & Proofreading',
        links: [
          { label: 'Book Editors', href: H('book-editors') },
          { label: 'Editors', href: H('book-editors') },
          { label: 'Proofreaders', href: BF('writing', 'proofread') },
          { label: 'Copy Editors', href: BF('writing', 'copy editing') },
        ],
      },
      {
        heading: 'Other',
        links: [
          { label: 'Article Writers', href: BF('writing', 'article') },
          { label: 'Journalists', href: BF('writing', 'journalist') },
          { label: 'Grant Writers', href: BF('writing', 'grant') },
          { label: 'Proposal Writers', href: BF('writing', 'proposal') },
          { label: 'Business Proposal Writers', href: BF('writing', 'business proposal') },
          { label: 'Reviews Writers', href: BF('writing', 'review') },
          { label: 'Transcriptionists', href: BF('writing', 'transcription') },
        ],
      },
    ],
    [
      {
        heading: 'Technical Writing',
        links: [
          { label: 'LinkedIn Specialists', href: BF('marketing', 'linkedin') },
          { label: 'Research Paper Writers', href: BF('writing', 'research paper') },
          { label: 'Technical Writers', href: BF('writing', 'technical') },
          { label: 'White Paper Writers', href: BF('writing', 'white paper') },
        ],
      },
      {
        heading: 'Translation',
        links: [
          { label: 'Translators', href: BF('writing', 'translation') },
          { label: 'Spanish Translators', href: BF('writing', 'spanish translation') },
          { label: 'Chinese Translators', href: BF('writing', 'chinese translation') },
          { label: 'Italian Translators', href: BF('writing', 'italian translation') },
          { label: 'French Translators', href: BF('writing', 'french translation') },
          { label: 'German Translators', href: BF('writing', 'german translation') },
          { label: 'Arabic Translators', href: BF('writing', 'arabic translation') },
          { label: 'Portuguese Translators', href: BF('writing', 'portuguese translation') },
        ],
      },
      {
        heading: 'Web Copywriting',
        links: [
          { label: 'Blog Writers', href: BF('writing', 'blog') },
          { label: 'Copywriters', href: H('copywriters') },
          { label: 'Headline Writers', href: BF('writing', 'headline') },
          { label: 'Ebook Writers', href: BF('writing', 'ebook') },
          { label: 'Content Writers', href: H('content-writers') },
          { label: 'SEO Writers', href: BF('writing', 'seo writing') },
          { label: 'Social Media Content Professionals', href: H('social-media-managers') },
          { label: 'Online Writers', href: BF('writing', 'online writer') },
          { label: 'Press Release Writers', href: BF('writing', 'press release') },
          { label: 'Product Description Writers', href: BF('writing', 'product description') },
        ],
      },
      {
        heading: 'Browse all',
        links: [{ label: 'All freelancers on Downwork', href: '/search/talent' }],
      },
    ],
  ],
}
